### ISSUE TITLE
/api/login: Function declared as capable of json but request http

### ISSUE THREAD

**Issue by webnah** [qnts/jwt_provider#1]
/api/register & api/me working well

not work: 
api/login

odoo 13: in fact inside controller type='http'

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>&lt;function JwtController.login at 0x10ea57d08&gt;, /api/login: Function declared as capable of handling request of
	type 'json' but called with a request of type 'http'</p>

**Comment by webnah** [comment]
postman: 
http://127.0.0.1:8069/api/login?email=user@demo.com&password=user
body:
{
"email":"user@demo.com",
"password":"user"
}

if use json post: result null

{
    "jsonrpc": "2.0",
    "id": null
}

**Comment by qnts** [comment]
@webnah Because odoo recognizes request with json data (via content-type) as json rpc. To work with http endpoint, you cannot send json data.

If you change the endpoint type to `json`, you have to make a json rpc request with body like:
```json
{
 "params": {
    "email": "user@demo.com",
    "...": "..."
  }
}
```

**Comment by prakashjain** [comment]
Facing same error attached screen shot
![Screenshot from 2021-07-15 11-15-56](https://user-images.githubusercontent.com/2025337/125735968-55ee9194-fb89-4973-bb95-07f7883d3be8.png)
