### ISSUE TITLE
Add ODOO_JWT_KEY

### ISSUE THREAD

**Issue by henrypham67** [qnts/jwt_provider#2]
Hi, i'm using JWT to authenticate my project but i can't get secret key `EXPORT ODOO_JWT_KEY="your_key"`. Can you show me step by step to do this?

**Comment by qnts** [comment]
@Heki67 What environment is your odoo instance running in? Are you using docker and docker compose?

**Comment by henrypham67** [comment]
@qnts no, i run it localy

**Comment by qnts** [comment]
Can you provide more info about what os and command to start odoo you're using?

**Comment by henrypham67** [comment]
I'm using windows 10 and this is how I run odoo `python odoo-bin -c G:\workspace\odoo\odoo.conf`

**Comment by qnts** [comment]
I don't know if this works or not but you should give it a try.

Open System Properties and set an environment var yourself before starting odoo.

![1](https://user-images.githubusercontent.com/4965816/85865938-d9a93300-b7f0-11ea-9d6b-3581f857df09.png)

**Comment by henrypham67** [comment]
oh it work. Thank you so much !!!

**Comment by Heki67** [comment]
it work when i do this in validator.py file
![image](https://user-images.githubusercontent.com/43398131/85873883-f7c86080-b7fb-11ea-9198-81ec7b5b1c00.png)

**Comment by qnts** [comment]
@Heki67 It's bad to store key in source code. That's why i moved it to env.
