### ISSUE TITLE
Request product.template Model Access Error

### ISSUE THREAD

**Issue by g3tl0st** [qnts/jwt_provider#4]
Hello, i tried access my api endpoint via ***localhost:8069/api/product.template*** after **Logged in**.

However i got ***Sorry, you are not allowed to access this document...***. 

**Code**
```
@http.route('/api/v1/product', auth='none', cors='*', type="json",  methods=['GET'], csrf=False)
    def index(self, **params):
        records = request.env['product.template'].search([])
```

How to solve this issue?? Thanks..

**Comment by qnts** [comment]
@g3tl0st sorry for the late catch-up, have you solved your issue right now?

**Comment by g3tl0st** [comment]
@qnts thanks so much for reply, yes i solved it now.
